name: oishimenu_app
description: OishiMenu - Restaurant Management Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Local Database
  sqflite: ^2.4.2
  path: ^1.9.1

  # Authentication & Security
  crypto: ^3.0.6

  # UI & Navigation
  go_router: ^12.1.3
  cached_network_image: ^3.3.0

  # Charts & Data Visualization
  fl_chart: ^0.65.0

  # Internationalization
  easy_localization: ^3.0.3

  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.20.2

  # UI Components
  material_design_icons_flutter: ^7.0.7296

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/menu-export.json

